import ExpansionPanel from '@material-ui/core/ExpansionPanel';
import ExpansionPanelDetails from '@material-ui/core/ExpansionPanelDetails';
import ExpansionPanelSummary from '@material-ui/core/ExpansionPanelSummary';
import Grid from '@material-ui/core/Grid';
import React, { useState } from 'react';
import styled from 'styled-components';

import { UnifiedHeading } from '../../components/AccentHeading';
import { Container } from '../../components/Container';
import { List, ListItem } from '../../components/List';
import { SectionLayout } from '../../components/SectionLayout';
import PlusIcon from '../../images/svg/add-black.svg';

const MaxWidth = styled.div`
  max-width: 500px;
`;

const Topic = styled.p`
  margin: 0;
  font-weight: 500;
`;

// eslint-disable-next-line no-unused-vars -- false positive error
const StyledPanel = styled(({ lastChild, ...other }) => (
  <ExpansionPanel {...other} />
))`
  && {
    box-shadow: none;
    background-color: transparent;
    margin: 0;
    border-bottom: 1px solid rgba(0, 0, 0, 0.125);

    ${({ lastChild }) => lastChild && 'border-bottom: 0;'}
    &.Mui-expanded {
      margin-top: 0;
    }

    &:before {
      display: none;
    }
  }
`;

const StyledSummary = styled(ExpansionPanelSummary)`
  && {
    padding: 60px 0;

    .MuiExpansionPanelSummary-content {
      margin: 0;
      padding-right: 30px;
      position: relative;
      display: flex;
      justify-content: space-between;
    }
  }
`;

const StyledPlusIcon = styled(PlusIcon)`
  width: 24px;
  height: 24px;
  margin-top: 2px;
  transition: transform 0.2s ease-out;
  ${({ isExpanded }) => isExpanded && 'transform: rotate(-225deg);'}
`;

const items = [
  {
    question: 'What is Forminer?',
    answer:
      'It’s a WYSIWYG React form builder. It allows you to build single- and multi-page forms, add custom validation, and configure conditional rendering. To put it in another way, It’s a ready-to-use set of React components for your project to have a fully functional Forminer in minutes.',
  },
  {
    question: 'How is Forminer different from Formium, TypeForm, or JotForm?',
    answer: [
      {
        content:
          'Forminer is a set of React components, and TypeForm/JotForm are SaaS products. The primary difference between these is that the Forminer becomes a part of your project and you integrate it directly in the code, while the others are external applications.',
        list: [
          'That implies you decide what you do with the data gathered with Forminer, while the others store it on their systems and give you options to access it.',
        ],
      },
      {
        content:
          'Formium is also a set of React components for rendering the built forms, but to build them, you have to interact with their SaaS backend. That’s where you create the forms and store the gathered data (by default). Forminer is distributed in its entirety as source code, including both the rendering of built forms and the Forminer itself.',
        list: [
          'The difference is that the Forminer definition (how the form looks like) is part of your app, can be adjusted, extended, and even generated by your app.',
          'Also, because there’s no backend Forminer contacts, it can also work offline (if your app supports that).',
        ],
      },
    ],
  },
  {
    question: 'Is Forminer Open Source?',
    answer:
      'No, Forminer is not open source. However, its core – uniforms – is a set of 100% open source (MIT licensed) packages, hosted on GitHub.',
  },
  {
    question: 'Is Forminer compatible with technologies other than React?',
    answer:
      'Forminer requires React to work, but you can embed it in your application even if it’s not there yet (e.g., it’s an Angular- or Vue-based app).',
  },
];

const StyledDetails = styled(ExpansionPanelDetails)`
  && {
    padding: 0;
  }
`;

export const FAQSection = () => {
  const [expanded, setExpanded] = useState('');

  const handleChange = panel => (event, newExpanded) => {
    setExpanded(newExpanded ? panel : '');
  };

  return (
    <SectionLayout alternativeBackground>
      <Container>
        <Grid spacing={3} container>
          <Grid xs={12} lg={6} item>
            <MaxWidth>
              <UnifiedHeading level={2} size="lg" isStrong>
                Frequently asked questions
              </UnifiedHeading>
            </MaxWidth>
          </Grid>
          <Grid xs={12} lg={6} item>
            {items.map(({ question, answer }, index) => {
              const isExpanded = expanded === `panel${index}`;

              return (
                <StyledPanel
                  key={`panel${index}`}
                  expanded={isExpanded}
                  onChange={handleChange(`panel${index}`)}
                  lastChild={items.length === index + 1}
                  square
                >
                  <StyledSummary aria-controls={`panel${index}d-content`}>
                    <Topic>{question}</Topic>
                    <StyledPlusIcon isExpanded={isExpanded} />
                  </StyledSummary>
                  <StyledDetails>
                    {Array.isArray(answer) ? (
                      <List>
                        {answer.map(({ content, list }) => (
                          <ListItem key={content}>
                            {content}
                            {Array.isArray(list) && (
                              <List>
                                {list.map(text => (
                                  <ListItem key={text}>{text}</ListItem>
                                ))}
                              </List>
                            )}
                          </ListItem>
                        ))}
                      </List>
                    ) : (
                      <p>{answer}</p>
                    )}
                  </StyledDetails>
                </StyledPanel>
              );
            })}
          </Grid>
        </Grid>
      </Container>
    </SectionLayout>
  );
};
