export const STRIPE_PAYMENT_LINKS = {
  TRIAL:
    'https://checkout.stripe.com/c/pay/cs_test_a1BI053Xp2JOveJIRSTdZECO5tkvHJXtsrzrbVngxCfn4QSHHl8sBOUlNO#fidkdWxOYHwnPyd1blpxYHZxWjA0SEhxbVxNQmcybzJvVHJNdjNWM2tEfFRKcmpKMTdPbUlvNzxXYF1%2FTEhLb0tmZDdcazJdS1dKMlxVdHBLZlx2dUxAMG1UYlJnajF2SXZEVGFKSEFVMnI3NTU1T0t2T0RcPScpJ3VpbGtuQH11anZgYUxhJz8ncWB2cVoxYnIwaFNmVGIzZldjM3I9cn0nKSd1d2BpamRhQ2prcSc%2FJ0xrcWB3J3gl',
};
